### ISSUE TITLE
WEBUi Download link seems broken

### ISSUE THREAD

**Issue by gtrdblt** [YunoHost-Apps/transmission_ynh#105]
Hi, 

Since the last update (3.00~ynh3), the webui view of the download folder is broken : 403 access denied. 

Here is the logs from nginx/mydomain-error.log : 

`2023/10/13 09:44:45 [error] 1012#1012: *486 "/home/yunohost.app/transmission/completed/index.html" is forbidden (13: Permission denied), client: xxxxxxxxxxx, server: mydomain, request: "GET /transmission/downloads/ HTTP/2.0", host: "mydomain", referrer: "https://mydomain/transmission/transmission/web/"`

The path seems correct in `/etc/nginx/conf.d/mydomain.conf.d/transmission.conf` : 

```
location /transmission/downloads/ {
  alias /home/yunohost.app/transmission/completed/;
  charset UTF-8;
  autoindex on;
  autoindex_exact_size off;
  more_clear_input_headers 'Accept-Encoding';

  # Include SSOWAT user panel.
  include conf.d/yunohost_panel.conf.inc;
}
```

So, I'm not really sure why it's broken now, but that's quite anoying as it was a useful feature for my use. 

If you could have a look at it, that would be awesome ;)

**Comment by ParleurA** [comment]
Same here.

And since the last upgrade, I also have an ugly font on WebUI.

**Comment by guigot** [comment]
Adding the execute permission to the directory's group transmission resolved the problem for me.
`chmod g+x /home/yunohost.app/transmission`

Modify the line `chmod -R 764 $data_dir` to `chmod -R 774 $data_dir` in the script files (install, restore, upgrade) is needed if this is the good solution.
