### ISSUE TITLE
Impossible to use external apps

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/transmission_ynh#14]
Hello, I would like to use Transmission with external apps (such as Transdroid on Android). However, these do not work anymore because of the YunoHost login panel I suspect. Same for the Transmission Remote GUI or CouchPotato.

It works well with transmission installs which use the standard login method though ...
I tried the steps suggested on the forum: https://forum.yunohost.org/t/transmission-remote-gui/138 but the end result is that my transmission app becomes publicly accessible, which is not ideal.

Any idea for a workaround? Or maybe a fork with the standard auth method?

Thanks

**Comment by stevenroose** [comment]
This is an issue that's found for a lot of Yunohost apps, and it's indeed cumbersome.

I think the only solution is to find a bittorrent daemon that supports LDAP authentication instead of requiring an http proxy.

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/476

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
