### ISSUE TITLE
enable logging

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/transmission_ynh#2]
man transmission-daemon
edit /etc/default/transmission-daemon
add " -e /var/log/transmission.log" in OPTIONS
create the log file and chown to debian-transmission

ideally, also set up logrotate (didn't look into this yet)

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/481

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
