### ISSUE TITLE
Transmission won't install on 2.6

### ISSUE THREAD

**Issue by mokas01** [YunoHost-Apps/transmission_ynh#26]
Hi

I tried to install Transmission on 2.6 and got warnings until the install finally failed. Here is the install in verbose mode. 

https://paste.yunohost.org/ivaceqicid.md

FYI : 
yunohost: 2.6.2
yunohost-admin: 2.6.0
moulinette: 2.6.0
ssowat: 2.6.5

Thanks

**Comment by M5oul** [comment]
It's a bug on YunoHost side.
Could you [open a bug here](https://dev.yunohost.org/projects/yunohost/issues/new).
Thanks.
