### ISSUE TITLE
open udp port

### ISSUE THREAD

**Issue by weber-s** [YunoHost-Apps/transmission_ynh#29]
hi,

I see in the install script that the tcp port is indeed open. However the udp one is not. It could be a good idea to open it as well. 

Samuël

**Comment by maniackcrudelis** [comment]
For more informations
https://en.wikipedia.org/wiki/Micro_Transport_Protocol

**Comment by anto1ne** [comment]
Can't we close this issue ? I think that udp and tcp port are both opened now
