### ISSUE TITLE
add watchdir option

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/transmission_ynh#3]
create /home/yunohost.transmission/watched
fix chown (debian-transmission:debian-transmission ?)
fix chmod (770 ?)

the idea is that another user (soon sickbeard ;) ) should be capable of writing stuff into it.

stop daemon
add :
   "watch-dir": "/home/yunohost.transmission/watched",
    "watch-dir-enabled": true
to /etc/transmission-daemon/settings.json
start daemon

(warning : the settings.json file is overwritten when daemon stops)

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/480

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
