### ISSUE TITLE
Disparition du bouton télécharger/The download button disappeared

### ISSUE THREAD

**Issue by Taekiro** [YunoHost-Apps/transmission_ynh#36]
French version :

Bonjour,
je viens de m'apercevoir que le bouton "télécharger" rajouté à Transmission par le script avait disparu, je suppose pendant une upgrade (je suis sûr qu'il était présent avant). Je ne sais pas d'où viens le problème, mais la modification de /usr/share/transmission/web/index.html n'a apparemment pas eu lieu.

English version :

Hi,
I just realised that the download button added to Transmission by the script disappeared, I suppose during an upgrade (I'm sure that it was present before). I don't know where the issue is coming from, but the modification of /usr/share/transmission/web/index.html isn't there now.

https://github.com/YunoHost-Apps/transmission_ynh/blob/09eba23f335a22c3b56f3bc90b4f221667fb280a/scripts/upgrade#L123

**Comment by Thomas830** [comment]
Hello,

Same problem here :-)

**Comment by alexAubin** [comment]
Same problem here :P

**Comment by maniackcrudelis** [comment]
Both with a new installation and an upgrade from the version of august 2017, I can't reproduce this issue.

**Comment by Taekiro** [comment]
Le bouton est réapparu avec la dernière mise à jour.
The button reappeared with the last app upgrade.

**Comment by guillaumefelter** [comment]
Le problème est réapparu pour moi / Same issue resurfaced.
Configuration :
- Debian Buster
- transmission-daemon 2.94 (d8e60ee44f)
- yunohost version: 4.0.8.3
