### ISSUE TITLE
Button point to HOST/SUBFOLDER and configuration only define /SUBFOLDER/ location

### ISSUE THREAD

**Issue by Madgui** [YunoHost-Apps/transmission_ynh#37]
FR:
J'utilise yunohost avec un autre port que le 443, et j'ai installé transmission dans un répertoire, et pas dans un domain dédié. Avec cette configuration, le bouton d'accès à l'application ne fonctionne pas.
Le lien pointe vers https://HOST/SUBFOLDER (sans /), alors que dans le fichier de configuration, c'est 
`location /SUBFOLDER/ {`
En rajoutant 
`location /SUBFOLDER {`
Ca fonctionne.

EN:
I use yunohost on a other port than 443, and I installed Transmission in a sub-folder. Using this configuration, the "square" application button don't work.
Actually he is pointing to something like https://HOST/SUBFOLDER (without the /), but this ressource is not defined in transmission.conf file, witch only contains this location:
`location /SUBFOLDER/ {`

If I add this location: it seems to work:
`location /SUBFOLDER {`

So, now, as soon as I don't upgrade my platform, it should work, yes ?

**Comment by maniackcrudelis** [comment]
Hello Madgui

I tried a new install of transmission in a sub path.
I didn't have any problem to access to the interface of transmission from the ynh portal.

Eventhough my configuration is the same than you.

**Comment by Madgui** [comment]
Hello Maniackcrudelis,
In my install I have set up the https port to 10443, perhaps it's because of that ?
Btw, I'm using 10443 because 443 is already used by sslh (allow me to have ssh and https on 443).
