### ISSUE TITLE
Configuration réécrite lors de la mise à jour/Configuration rewritten when updated

### ISSUE THREAD

**Issue by billietl** [YunoHost-Apps/transmission_ynh#41]
French version :

Bonjour,
je m'apperçoit que la configuration de transmission est réécrite lors de la mise à jour du module, ce qui est très génant (par exemple si on a mis en place une limitation de débits, du nombre de peers acceptés ou autre).
Est-il possible d'enregistrer dans yunohost les clés de configuration à garder/modifier/réécrire lors des mises à jour ? De ce fait, seules les clés non-spécifiées sont potentiellement affectées par le changement des valeurs par défaut lors des mises à jour ?

Cordialement,
Louis

English version :

Hi,
I realise that transmisison's configuration is rewritten when updating the module, which is verry embarrasing (for example if we have set up throughput limitation, accepted peers number or any other thing).
Is it possible to register in yunohost the configuration keys to keep/modify/rewrite when updating ? That way, only the non-specified keys might be affected by default value changes when updating ?
Best regards,
Louis

**Comment by billietl** [comment]
Je viens de jeter un oeil au script d'upgrade et me rends compte que ma proposition ne sera pas forcement ergonomique. Peut-être serait-ce plus simple de charger le fichier de configuration en place avant update, puis de reporter dans le nouveau fichier de configuration des valeurs qui ont changé ?

I just looked at the upgrade script and I realised that what I proposed may not be really practical. Maybe would it be simpler to load the configuration file before updating, then set the changing values in the new file ?

**Comment by maniackcrudelis** [comment]
Hi billietl

Actually, your config file was saved during the upgrade and keep aside.
Because we know that you could have a modified config file, we don't overwrite it.

Anyway, I understand your problem, especially because I have the same with transmission...
It could be better to ask to an user if he want to keep his config file or not, but unfortunately we don't have any way to do that yet.
And, because there could be some modifications really important in the upgraded file, we have chosen to keep the new file over the old one.

I hope that we'll have a way to let the users decide which is better for them.

**Comment by billietl** [comment]
Maybe we could use ynh_app_setting_set for this ? And when upgrading, we parse each key in the new configuration file, try to fetch the corresponding key in ynh_app_setting and rewrite if any ?
Like so, in my case (I've set alt-speed-time-begin and alt-speed-time-end), all I'd have to do is : 
```
ynh_app_setting_set transmission alt-speed-time-begin 1020
ynh_app_setting_set transmission alt-speed-time-begin 540
```
And I would be done.

**Comment by maniackcrudelis** [comment]
Adding each modification as a key in the settings.yml could be really tricky, How do you handle multiple lines modifications, why if you forgot one, what if a key has the same name that an other one. Etc...

However, adding a key in your settings.yml to say that you don't want to replace your files could be a good idea, in the meantime for a global options easily accessible.
