### ISSUE TITLE
User settings lost after upgrade

### ISSUE THREAD

**Issue by Gofannon** [YunoHost-Apps/transmission_ynh#55]
Hello,

After an upgrade of the package, user settings are overwritten. See https://github.com/YunoHost-Apps/transmission_ynh/blob/master/scripts/upgrade#L110

**Comment by maniackcrudelis** [comment]
Huh yep, as usual.
Also the settings are backed up before https://github.com/YunoHost-Apps/transmission_ynh/blob/master/scripts/upgrade#L100

That's the usual behavior for all our apps.

**Comment by Gofannon** [comment]
Oh well, I'm too used to DokuWiki being able to have a configuration space dedicated to YunoHost and one space for user settings...
