### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by Brownie2002** [YunoHost-Apps/transmission_ynh#63]
Hello,

I cannot install transmission, I have a failed dependency but I do not use Emby like the other guy...

admin@XXXX:/var/cache/apt/archives$ sudo yunohost log display 20190603-220537-app_install-transmission
description: Install 'transmission' application
log_path: /var/log/yunohost/categories/operation/20190603-220537-app_install-transmission.log
logs: 
  - 2019-06-03 22:06:35,870: DEBUG - + [[ -n /tmp/tmp.ZjywnOQFOR ]]
  - 2019-06-03 22:06:35,871: DEBUG - + rm -rf /tmp/tmp.ZjywnOQFOR
  - 2019-06-03 22:06:36,172: DEBUG - + ynh_package_is_installed transmission-ynh-deps
  - 2019-06-03 22:06:36,173: DEBUG - + local legacy_args=p
  - 2019-06-03 22:06:36,174: DEBUG - + args_array=([p]=package=)
  - 2019-06-03 22:06:36,175: DEBUG - + declare -Ar args_array
  - 2019-06-03 22:06:36,176: DEBUG - + local package
  - 2019-06-03 22:06:36,177: DEBUG - + ynh_handle_getopts_args transmission-ynh-deps
  - 2019-06-03 22:06:36,178: DEBUG - + set +x
  - 2019-06-03 22:06:36,380: DEBUG - + echo '! Helper used in legacy mode !'
  - 2019-06-03 22:06:36,381: DEBUG - + set +x
  - 2019-06-03 22:06:36,382: DEBUG - + ynh_wait_dpkg_free
  - 2019-06-03 22:06:36,383: DEBUG - + local try
  - 2019-06-03 22:06:36,385: DEBUG - ++ seq 1 17
  - 2019-06-03 22:06:36,386: DEBUG - + for try in `seq 1 17`
  - 2019-06-03 22:06:36,387: DEBUG - + sudo lsof /var/lib/dpkg/lock
  - 2019-06-03 22:06:37,792: DEBUG - + local dpkg_dir=/var/lib/dpkg/updates/
  - 2019-06-03 22:06:37,793: DEBUG - ++ ls -1 /var/lib/dpkg/updates/
  - 2019-06-03 22:06:37,894: DEBUG - + read dpkg_file
  - 2019-06-03 22:06:37,896: DEBUG - + echo ''
  - 2019-06-03 22:06:37,897: DEBUG - + grep -Pq '^[[:digit:]]+$'
  - 2019-06-03 22:06:37,897: DEBUG - + read dpkg_file
  - 2019-06-03 22:06:37,898: DEBUG - + return 0
  - 2019-06-03 22:06:37,899: DEBUG - + dpkg-query -W -f '${Status}' transmission-ynh-deps
  - 2019-06-03 22:06:37,900: DEBUG - + grep -c 'ok installed'
  - 2019-06-03 22:06:38,102: DEBUG - + ynh_die '--message=Unable to install dependencies'
  - 2019-06-03 22:06:38,103: WARNING - Unable to install dependencies
  - 2019-06-03 22:06:38,105: DEBUG - + local legacy_args=mc
  - 2019-06-03 22:06:38,106: WARNING - !!
  - 2019-06-03 22:06:38,107: DEBUG - + args_array=([m]=message= [c]=ret_code=)
  - 2019-06-03 22:06:38,108: WARNING -   transmission's script has encountered an error. Its execution was cancelled.
  - 2019-06-03 22:06:38,109: DEBUG - + declare -Ar args_array
  - 2019-06-03 22:06:38,110: WARNING - !!
  - 2019-06-03 22:06:38,111: DEBUG - + local message
  - 2019-06-03 22:06:38,112: WARNING - /usr/share/yunohost/helpers.d/print: line 10: args_array: readonly variable
  - 2019-06-03 22:06:38,113: DEBUG - + local ret_code
  - 2019-06-03 22:06:38,114: DEBUG - + ynh_handle_getopts_args '--message=Unable to install dependencies'
  - 2019-06-03 22:06:38,115: DEBUG - + set +x
  - 2019-06-03 22:06:38,115: DEBUG - + echo 'Unable to install dependencies'
  - 2019-06-03 22:06:38,117: DEBUG - + exit 1
  - 2019-06-03 22:06:38,118: DEBUG - + ynh_exit_properly
  - 2019-06-03 22:06:38,119: DEBUG - + local exit_code=1
  - 2019-06-03 22:06:38,120: DEBUG - + '[' 1 -eq 0 ']'
  - 2019-06-03 22:06:38,121: DEBUG - + trap '' EXIT
  - 2019-06-03 22:06:38,122: DEBUG - + set +eu
  - 2019-06-03 22:06:38,122: DEBUG - + echo -e '!!\n  transmission'\''s script has encountered an error. Its execution was cancelled.\n!!'
  - 2019-06-03 22:06:38,123: DEBUG - + type -t ynh_clean_setup
  - 2019-06-03 22:06:38,124: DEBUG - + ynh_die
  - 2019-06-03 22:06:38,125: DEBUG - + local legacy_args=mc
  - 2019-06-03 22:06:38,127: DEBUG - + args_array=([m]=message= [c]=ret_code=)
metadata: 
  args: 
    app: transmission
    args: None
    force: False
    label: None
    no_remove_on_failure: False
  ended_at: 2019-06-03 22:06:38
  env: 
    YNH_APP_ARG_DOMAIN: xxxxx.xyz
    YNH_APP_ARG_PATH: /torrent
    YNH_APP_ID: transmission
    YNH_APP_INSTANCE_NAME: transmission
    YNH_APP_INSTANCE_NUMBER: 1
    YNH_CWD: /var/cache/yunohost/from_file/transmission_ynh-08fb61e693bed5b92cd78e94790d9be585efb3b4/scripts
    YNH_STDINFO: /tmp/tmptief_O/stdinfo
    YNH_STDRETURN: /tmp/tmph7CUpN/stdreturn
  error: An unexpected error occured: shell command return code: 1
  operation: app_install
  related_to: 
    - app
    - transmission
  started_at: 2019-06-03 22:05:37
  success: False
metadata_path: /var/log/yunohost/categories/operation/20190603-220537-app_install-transmission.yml
name: 20190603-220537-app_install-transmission

If I can give more log .... just ask. I tried to install manually, then purge, then retry ... No solutions.

**Comment by maniackcrudelis** [comment]
Hi Brownie2002

A complete log would be great indeed.
Especially what apt was doing. We don't have much info here about it.

**Comment by Brownie2002** [comment]
Hello,
Here is the complete log : [https://paste.yunohost.org/raw/fevusegohu](url)
Regards

**Comment by maniackcrudelis** [comment]
> "dpkg-deb (subprocess): compressing tar member: lzma error: **Cannot allocate memory**"

I guess that where your error is. You lack of free RAM.

**Comment by Brownie2002** [comment]
Well done ! I stopped other services and it worked smooth. I didn't suspected that the installer needed RAM like this. Thank you !
