### ISSUE TITLE
Delete torrent and it's files

### ISSUE THREAD

**Issue by Saimyx** [YunoHost-Apps/transmission_ynh#69]
With 2.92 Transmission, I have a problem with the option " trash data and remove from list ".
Transmission delete torrent in the list, but not the files...

**Comment by maniackcrudelis** [comment]
Could you check the permission on a file that you know wasn't removed by Transmission ?

**Comment by Saimyx** [comment]
I'm sorry, I can't because I had deleted files with ssh...
If it happens again I will check that and comment here.

**Comment by yalh76** [comment]
tested on last version and now it's working
