### ISSUE TITLE
Wish : ajout du controle du port 51413 dans le diagnostique automatique

### ISSUE THREAD

**Issue by anto1ne** [YunoHost-Apps/transmission_ynh#71]
Bonjour,

L'installation de transmission sur yunohost nécessite l'ouverture du port 51413.
Actuellement ce port n'est pas controlé par l'auto-diagnostique.

Il serai intéressant d'ajouter le controle de ce port lorsque transmission est installé.

https://github.com/YunoHost/issues/issues/1643

**Comment by yalh76** [comment]
It had been added in https://github.com/YunoHost-Apps/transmission_ynh/pull/85
