### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by nick69999** [YunoHost-Apps/transmission_ynh#83]
Hi !

I have a problem with permissions on transmission  on my yunohost. When I upload a torrent file, it start and the loading too, I see the connexion to the others peers, but after less than 10% loading, a text say ; " Permission denied (/home/yunohost.transmission/completed/mummy_family_pictures"

And nothing, I tried to upload some another torrents, reboot my server, manage permissions with ynh interface, re-install the app 5 times, change domain or sub-domain, but nothing, always this problem.

On my old ynh server, it worked perfectly, but on my new I have this problem. the only difference is what I use a IP failover.
My ynh is based on debian 10.

Anyone can help me ? 

Thank you and sorry for my English level :)

**Comment by yalh76** [comment]
owner should be debian-transmission
group: www-data
and chmod: rwxrwxr-x

**Comment by tituspijean** [comment]
Closing for lack of follow-up. Feel free to reopen if needed. ;)

**Comment by seedrick** [comment]
I just noticed I'm having this issue as of yesterday. I have my download folders set to my NAS and never had permissions issues before now.
