### ISSUE TITLE
Transmission and 3rd apps

### ISSUE THREAD

**Issue by punkrockgirl** [YunoHost-Apps/transmission_ynh#89]
Hi,

I'm trying to use Transmission through one of the many apps for Android but I haven't been successful. I can access the web UI, though.

I am aware that there is an issue [#14] with the same problem, but that one was opened in 2014 so I was wondering if any progress had been made, it remains the same, or I misconfigured something.

I have set up the following apps with [the data shown on this github](https://github.com/YunoHost-Apps/transmission_ynh#additionnal-informations) and this is what happens:

- Transdroid: _Internal error building request_
- Transmission Remote: spins but never loads anything
- Tremotesf: _Parsing error_

Raspberry Pi 4 [2Gb] 32-bit
YUNHOST: 4.2.6 (SSH & webadmin)
Transmission: 1.0~ynh4

I have modified the .json file to change the downloads directory, but that's all.

Thanks

**Comment by Suniron** [comment]
Hey,

I got same problem here with a raspberry pi4 & raspbian 64 bits & yunohost latest.

**Comment by avDuma** [comment]
Same issue for me with Transdroid. I can reach by browser using https://my.host.com/transmission but not through Transdroid app

**Comment by tituspijean** [comment]
After some investigation, I have pin-pointed the issue to the fact that YunoHost's SSO will interfere in the page loading, asking for a credentials. It is unexpected by these apps, and their connection crashes.

Option for users:
* Use apps that can handle HTTP Basic auth directly while initiating the connection. That makes the SSO seemingly transparent. I do not know if such apps exist for Transmission.

Option for us packagers:
1. Make the `/transmission/transmission/rpc` path public ***AND*** enable RPC authentication system (Transmission's own username and password for its RPC). If this is not enabled, then the app will be accessible by anybody.
2. Update the README and maybe make the RPC password settable, or accessible in a config panel

Side

**Comment by Kabraxist** [comment]
Doesn't HTTP Basic Auth go by https://username:password@yunohostdomain/ ? I can't proceed with that even in the browser. Is there a Yunohost option to enable HTTP Basic Auth?

**Comment by N-Upchurch** [comment]
Is this issue still present? I'm trying to connect via Tremotesf and I'm receiving "parse error."

**Comment by Salamandar** [comment]
It should be fixed since manifestv2.

**Comment by xabirequejo** [comment]
Instructions say:

> - Remote host: Your domain or IP address (don't add folder)
> - Port: 443
> - SSL: Enabled
> - User: Your Yunohost Username
> - Password: Password of the Yunohost User above
> - RPC Path: /torrent/transmission/rpc (if you used the standard folder)

Tremotesf wouldn't work with the path above, but it did with `/transmission/rpc`

**Comment by Salamandar** [comment]
Yes, instructions should say `RPC Path: <transmission path>/transmission/rpc`, but you figured it out on your own ;)
