### ISSUE TITLE
Wrong permission on folder creation

### ISSUE THREAD

**Issue by Vitriia** [YunoHost-Apps/transmission_ynh#94]
### Describe the bug

Transmission is creating folder with drw-rwxr-x+ (102 in umask) rights preventing Transmission any writing inside folders.
(Files are -rw-rw-r--+)

### Context

Transmission 2.94~ynh1

### Steps to reproduce

Install Transmission
Add & start a torrent with folders 
Transmission will grap a few Mo then raise a "Permission denied" error

### Expected behavior

Creating folders with drwxrwx-r-x rights

### Logs

In settings.json (same value in this repo settings.json), the parameter for umask is 18. 
Which seem strange as far i understand umask notation.

Also, Transmission seem to ignore the umask value after :
Stopping transmission-daemon
Modifiying settings.json
Starting transmission-daemon

Tried with 002 and 000 umaks and transmission is still creating folders with the same rights

**Comment by tituspijean** [comment]
To get a complete picture of the issue please provide the output of `getfacl <the_path>`.

**Comment by Vitriia** [comment]
getfacl result on the Transmission created folder :
```# file: My_Folder/
# owner: debian-transmission
# group: debian-transmission
user::rw-
group::rwx
group:multimedia:rwx
mask::rwx
other::r-x
default:user::rw-
default:group::rwx
default:group:multimedia:rwx
default:mask::rwx
default:other::r-x```

**Comment by tituspijean** [comment]
Cannot replicate the `default:user::rw-` instead of `default:user::rwx`. Closing.

Feel free to reopen if it consistently happens.
