### ISSUE TITLE
Unable to connect with RPC

### ISSUE THREAD

**Issue by odolbeau** [YunoHost-Apps/transmission_ynh#97]
Hi!

I installed the application through cli with the following command:
`yunohost app install transmission -a "domain=transmission.custom.domain&path=/"`

Everything works fine in web! :ok_hand: 

I would like to connect using transmission-remote-gtk using RPC. This is the configuration I use:
![image](https://user-images.githubusercontent.com/680206/205303777-90b2e93a-dde8-44f8-ae8d-b0e2aa647b7d.png)

This is the error I get:
![image](https://user-images.githubusercontent.com/680206/205303993-756914a8-e6dc-4c7c-81ab-1d278e63508e.png)

This 302 redirect probably is a redirection to the SSO login page (at least, this is what I get using `curl`).

Another point: according to the README, I should use my username but in the transmission settings file (located in `/etc/transmission-daemon/settings.json`) I get `rpc-username: transmission`.

Did I miss something?

**Comment by UnicodeApocalypse** [comment]
### Temporary fix for curretn users
A permission is missing, you can fix it by adding it to `/etc/ssowat/conf.json` : 
````
"transmission.rpc": {
    "auth_header": true,
    "label": "Transmission (RPC)",
    "public": true,
    "show_tile": false,
    "uris": [
        "example.com/choosen_path/transmission/rpc"
    ],
    "use_remote_user_var_in_nginx_conf": true,
    "users": []
 }
````
* Replace `example.com` with your domain
* Replace `choosen_path` with the path you defined for transmission
---


### Fix transmission install
I thought making a PR to fix it but i'm totally new to YunoHost and I'm not sure about the install command.
Files to fix seems to be : 
* [/scripts/install](https://github.com/YunoHost-Apps/transmission_ynh/tree/master/scripts/install)
* [/scripts/upgrade](https://github.com/YunoHost-Apps/transmission_ynh/tree/master/scripts/upgrade)


**And a command like this one should fix it :** 
`ynh_permission_create --permission="rpc" --url="/transmission/rpc" --allowed="visitors" --show_tile="false" --protected="true"`

Problem is it doesn't seem to define `use_remote_user_var_in_nginx_conf` value and I can't find the right parameter in YunoHost doc

**Comment by Salamandar** [comment]
It should be fixed since manifestv2.
